services:

  redis:
    image: redis:alpine
    container_name: smartsure-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - smartsure-network
    deploy:
      resources:
        limits:
          memory: 256M

  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartsure-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: smartsure
      RABBITMQ_DEFAULT_PASS: smartsure
    networks:
      - smartsure-network
    deploy:
      resources:
        limits:
          memory: 512M

  zipkin:
    image: openzipkin/zipkin
    container_name: smartsure-zipkin
    ports:
      - "9411:9411"
    networks:
      - smartsure-network
    deploy:
      resources:
        limits:
          memory: 256M

  prometheus:
    image: prom/prometheus
    container_name: smartsure-prometheus
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - smartsure-network
    deploy:
      resources:
        limits:
          memory: 512M

  loki:
    image: grafana/loki:latest
    container_name: smartsure-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - smartsure-network
    deploy:
      resources:
        limits:
          memory: 256M

  grafana:
    image: grafana/grafana:latest
    container_name: smartsure-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - smartsure-network
    deploy:
      resources:
        limits:
          memory: 512M



networks:
  smartsure-network:
    driver: bridge

volumes:
  redis-data:
