package com.smartSure.claimService.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Claim entity — Digital-First architecture.
 *
 * Flow:
 *  1. Customer fills digital form → DRAFT created with all incident details
 *  2. Backend auto-generates PDF from form data (no manual form download)
 *  3. Customer uploads evidence photos only (one upload, not three)
 *  4. Customer gives digital consent (replaces physical signature)
 *  5. Customer submits → SUBMITTED
 *  6. Admin reviews → APPROVED / REJECTED (with mandatory remarks on rejection)
 *  7. RabbitMQ event → PaymentService payout + email notification
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "claim")
public class Claim {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private Long policyId;

    @Column(nullable = false)
    private Long userId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status;

    // ── Claim Amount ──────────────────────────────────────────────────────────
    // Actual amount customer is claiming — NOT full coverage amount
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;

    // ── Incident Details (replaces manual claim form) ──────────────────────────
    @Column(columnDefinition = "TEXT")
    private String description;

    private LocalDate incidentDate;

    @Enumerated(EnumType.STRING)
    private IncidentType incidentType;      // ACCIDENT, THEFT, FIRE, HEALTH, NATURAL_DISASTER, OTHER

    private String incidentLocation;        // city/address where incident occurred

    // Health claim specific
    private String hospitalName;
    private String treatmentType;           // INPATIENT, OUTPATIENT, EMERGENCY

    // Auto claim specific
    private String vehicleNumber;
    private String garageRepairShop;

    // Theft/Accident specific
    private String policeReportNumber;
    private String witnessName;
    private String witnessContact;

    // ── Auto-Generated PDF (generated by backend from form data) ─────────────
    // Customer never downloads/fills/scans a form — backend generates it
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "fileName", column = @Column(name = "claim_form_name")),
            @AttributeOverride(name = "fileType", column = @Column(name = "claim_form_type")),
            @AttributeOverride(name = "filePath", column = @Column(name = "claim_form_path"))
    })
    private FileData claimForm;

    private Boolean pdfGenerated = false;

    // ── Evidence Upload (only manual upload required) ──────────────────────────
    // Customer uploads photos/scans of receipts, bills, photos of damage
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "fileName", column = @Column(name = "evidence_name")),
            @AttributeOverride(name = "fileType", column = @Column(name = "evidence_type")),
            @AttributeOverride(name = "filePath", column = @Column(name = "evidence_path"))
    })
    private FileData evidences;

    // ── Aadhaar — replaced by OTP at registration, no scan needed ─────────────
    // Kept for backward compatibility — optional now
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "fileName", column = @Column(name = "aadhaar_name")),
            @AttributeOverride(name = "fileType", column = @Column(name = "aadhaar_type")),
            @AttributeOverride(name = "filePath", column = @Column(name = "aadhaar_path"))
    })
    private FileData aadhaarCard;

    // ── Digital Consent (replaces physical signature — IT Act 2000 compliant) ─
    private Boolean consentGiven = false;
    private LocalDateTime consentTimestamp;
    private String consentIpAddress;

    // ── Admin Decision ────────────────────────────────────────────────────────
    @Column(columnDefinition = "TEXT")
    private String adminRemarks;
    private Long reviewedBy;                // admin userId
    private LocalDateTime reviewedAt;

    // ── Auto Approval ─────────────────────────────────────────────────────────
    private Boolean autoApproved = false;

    // ── Audit ─────────────────────────────────────────────────────────────────
    private LocalDateTime timeOfCreation;
    private LocalDateTime lastUpdatedAt;

    @PrePersist
    public void prePersist() {
        this.timeOfCreation = LocalDateTime.now();
        this.lastUpdatedAt  = LocalDateTime.now();
        if (this.status == null) {
            this.status = Status.DRAFT;
        }
        if (this.pdfGenerated == null) {
            this.pdfGenerated = false;
        }
        if (this.consentGiven == null) {
            this.consentGiven = false;
        }
        if (this.autoApproved == null) {
            this.autoApproved = false;
        }
    }

    @PreUpdate
    public void preUpdate() {
        this.lastUpdatedAt = LocalDateTime.now();
    }

    // ── Incident Type Enum ────────────────────────────────────────────────────
    public enum IncidentType {
        ACCIDENT,
        THEFT,
        FIRE,
        HEALTH,
        NATURAL_DISASTER,
        PROPERTY_DAMAGE,
        OTHER
    }
}